//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AccountCreateProcessor : NSObject
{
}

- (id)getUserID;
- (id)valueForKey:(id)arg1 fromQueryItems:(id)arg2;
- (_Bool)validateResponse:(id)arg1 withOptions:(id)arg2 withScheme:(id)arg3 withPath:(id)arg4;

@end

