//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double width;
    double height;
};

struct GraphicsApp;

struct Input {
    CDUnknownFunctionPointerType *_field1;
    struct InputHandler *_field2;
    struct InputHandler *_field3;
    struct map<eastl::basic_string<char, eastl::allocator>, jag::input::InputHandler *, eastl::less<eastl::basic_string<char, eastl::allocator>>, eastl::allocator> _field4;
    struct list<eastl::basic_string<char, eastl::allocator>, eastl::allocator> _field5;
    float _field6;
    float _field7;
    id _field8;
    void *_field9;
};

struct InputHandler;

struct ListNodeBase {
    struct ListNodeBase *_field1;
    struct ListNodeBase *_field2;
};

struct NSMapTable {
    Class _field1;
};

struct NSMutableDictionary {
    Class _field1;
};

struct OpenGLView {
    CDUnknownFunctionPointerType *_field1;
    struct weak_ptr<jag::OpenGLView> _field2;
    struct GraphicsApp *_field3;
    struct Window *_field4;
    _Bool _field5;
    _Bool _field6;
    _Bool _field7;
    _Bool _field8;
    float _field9;
    unsigned int _field10;
    unsigned int _field11;
    unsigned int _field12;
    unsigned int _field13;
    id _field14;
};

struct Window;

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct allocator;

struct less<eastl::basic_string<char, eastl::allocator>>;

struct list<eastl::basic_string<char, eastl::allocator>, eastl::allocator> {
    struct ListNodeBase _field1;
    struct allocator _field2;
};

struct map<eastl::basic_string<char, eastl::allocator>, jag::input::InputHandler *, eastl::less<eastl::basic_string<char, eastl::allocator>>, eastl::allocator> {
    struct less<eastl::basic_string<char, eastl::allocator>> _field1;
    struct rbtree_node_base _field2;
    unsigned long long _field3;
    struct allocator _field4;
};

struct rbtree_node_base {
    struct rbtree_node_base *_field1;
    struct rbtree_node_base *_field2;
    struct rbtree_node_base *_field3;
    char _field4;
};

struct ref_counter_base;

struct sockaddr {
    unsigned char _field1;
    unsigned char _field2;
    char _field3[14];
};

struct weak_ptr<jag::OpenGLView> {
    struct ref_counter_base *_field1;
    struct OpenGLView *_field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    long long _field1;
    void *_field2;
    CDUnknownFunctionPointerType _field3;
    CDUnknownFunctionPointerType _field4;
    CDUnknownFunctionPointerType _field5;
} CDStruct_e097db04;

