//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FederatedLogin : NSObject
{
    NSString *m_playerID;
    _Bool m_isAuthenticated;
    _Bool m_isUnderAge;
    NSString *m_playerName;
    _Bool responseSent;
    NSString *m_publicKeyUrl;
    NSString *m_timestamp;
    NSString *m_signature;
    NSString *m_salt;
}

+ (id)sharedFederatedLogin;
- (void).cxx_destruct;
- (void)isGameCentreIDLinked:(id)arg1 response:(CDUnknownBlockType)arg2;
- (void)getAccessTokens:(id)arg1 callback:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)enableGameCenter:(id)arg1 response:(CDUnknownBlockType)arg2;
- (_Bool)isAuthenticated;
- (void)setup;

@end

