//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SKPaymentTransactionObserver-Protocol.h"

@class NSMutableArray, NSString;

@interface IAPurchaseHelper : NSObject <SKPaymentTransactionObserver>
{
    CDUnknownBlockType purchaseSubscriberResponse;
    CDUnknownBlockType purchaseSubscriberError;
    CDUnknownBlockType purchaseSubscriberCompleted;
    CDUnknownBlockType inCompleteTransactionResponse;
    CDUnknownBlockType inCompleteTransactionError;
    CDUnknownBlockType inCompleteTransactionCompleted;
    NSMutableArray *_productsPurchased;
    NSMutableArray *_productsRestored;
    NSString *_message;
    NSString *_purchasedID;
    long long _status;
}

+ (id)sharedInstance;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *purchasedID; // @synthesize purchasedID=_purchasedID;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSMutableArray *productsRestored; // @synthesize productsRestored=_productsRestored;
@property(retain, nonatomic) NSMutableArray *productsPurchased; // @synthesize productsPurchased=_productsPurchased;
- (void).cxx_destruct;
- (void)completeTransaction:(id)arg1;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(id)arg1;
- (void)paymentQueue:(id)arg1 restoreCompletedTransactionsFailedWithError:(id)arg2;
- (void)paymentQueue:(id)arg1 removedTransactions:(id)arg2;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)setIncompleteTransactionSignal:(CDUnknownBlockType)arg1 error:(CDUnknownBlockType)arg2 complete:(CDUnknownBlockType)arg3;
- (void)purchaseProduct:(id)arg1 response:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3 complete:(CDUnknownBlockType)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

