//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "StoreManagerDelegate-Protocol.h"

@class NSMutableArray, StoreManager;

@interface InAppBillingWrapper : NSObject <StoreManagerDelegate>
{
    StoreManager *storeManager;
    NSMutableArray *products;
    NSMutableArray *incompleteTransactions;
    NSMutableArray *nonActionableTransactions;
    NSMutableArray *actionableTransactions;
    CDUnknownBlockType productSubscriberResponse;
    CDUnknownBlockType productSubscriberError;
    CDUnknownBlockType productSubscriberCompleted;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)onProductsLoadError:(id)arg1;
- (void)onProductsLoaded:(id)arg1;
- (void)completeTransaction:(id)arg1;
- (void)completeTransactions:(id)arg1 transactions:(id)arg2;
- (id)getNonActionableIncompleteTransactions;
- (id)getIncompleteTransactions;
- (_Bool)isIncompleteTransactions;
- (void)applyPendingTransactions:(id)arg1 transactions:(id)arg2 purchaseType:(id)arg3 error:(CDUnknownBlockType)arg4 complete:(CDUnknownBlockType)arg5;
- (void)filterAndApplyPendingTransactions:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)initializeIncompleteTransactions:(id)arg1;
- (void)productTrialAvailable:(id)arg1 response:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3;
- (void)purchaseProduct:(id)arg1 response:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3 complete:(CDUnknownBlockType)arg4;
- (void)fetchProductsFromStore:(id)arg1 response:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3 complete:(CDUnknownBlockType)arg4;
- (id)fetchTransactionReceipts;
- (void)removePaymentObserver;
- (void)initPaymentObserver;
- (id)init;

@end

