//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UITextField;

@interface InputDelegate : UIResponder <UITextFieldDelegate>
{
    _Bool textFieldEditing;
    UITextField *textField;
    struct Input *inputHAL;
}

@property(nonatomic) struct Input *inputHAL; // @synthesize inputHAL;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField;
@property(nonatomic) _Bool textFieldEditing; // @synthesize textFieldEditing;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)dealloc;
- (id)init:(id)arg1 ParentView:(id)arg2 InputHAL:(struct Input *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

