//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface JagexCategory : NSObject
{
    long long categoryID;
    NSString *name;
    NSString *imageCollapsed;
    NSString *imageExpanded;
    NSString *shortDescription;
    NSString *longDescription;
    NSMutableArray *products;
}

@property(retain, nonatomic) NSMutableArray *products; // @synthesize products;
@property(retain, nonatomic) NSString *longDescription; // @synthesize longDescription;
@property(retain, nonatomic) NSString *shortDescription; // @synthesize shortDescription;
@property(retain, nonatomic) NSString *imageExpanded; // @synthesize imageExpanded;
@property(retain, nonatomic) NSString *imageCollapsed; // @synthesize imageCollapsed;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(nonatomic) long long categoryID; // @synthesize categoryID;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)loadProductsFromArray:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithName:(long long)arg1 name:(id)arg2 imageCollapsed:(id)arg3 imageExpanded:(id)arg4 shortDescription:(id)arg5 longDescription:(id)arg6 products:(id)arg7;

@end

