//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SKProduct;

@interface JagexProduct : NSObject
{
    _Bool recommended;
    _Bool available;
    _Bool _discountElegibility;
    NSString *productId;
    NSString *title;
    NSString *subtitle;
    SKProduct *skProduct;
}

@property(nonatomic) _Bool discountElegibility; // @synthesize discountElegibility=_discountElegibility;
@property(retain, nonatomic) SKProduct *skProduct; // @synthesize skProduct;
@property(nonatomic) _Bool available; // @synthesize available;
@property(nonatomic) _Bool recommended; // @synthesize recommended;
@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) NSString *productId; // @synthesize productId;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)setDiscountEligibility;
- (id)initProductFromDictionary:(id)arg1;
- (id)initWithProductId:(id)arg1 title:(id)arg2 subTitle:(id)arg3 recommended:(_Bool)arg4 available:(_Bool)arg5 product:(id)arg6;

@end

