//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OIDAuthStateChangeDelegate-Protocol.h"
#import "OIDAuthStateErrorDelegate-Protocol.h"

@class NSString;

@interface MobileAuthStateManager : NSObject <OIDAuthStateChangeDelegate, OIDAuthStateErrorDelegate>
{
}

- (void)authState:(id)arg1 didEncounterAuthorizationError:(id)arg2;
- (void)didChangeState:(id)arg1;
- (void)loadState;
- (void)saveState;
- (void)setAuthState:(id)arg1;
- (id)getAuthState;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

