//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BillingApis, FederatedLogin, MobileAttribution, MobileAuthConfiguration, MobileAuthStateManager, MobileBrowserViewController;

@interface MobileAuth : NSObject
{
    MobileAuthStateManager *m_authStateManager;
    MobileAuthConfiguration *m_mobileAuthConfig;
    MobileAttribution *m_mobileAttribution;
    MobileBrowserViewController *m_browser;
    BillingApis *m_billingApis;
    FederatedLogin *m_federatedLogin;
    _Bool m_federatedAvailable;
}

- (void).cxx_destruct;
- (void)storeTokens:(id)arg1 refreshToken:(id)arg2 expirationDate:(id)arg3 callback:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)safariCallback:(id)arg1;
- (void)createAccount:(id)arg1 URL:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)sendEvent:(id)arg1 withParams:(id)arg2;
- (void)logout:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (_Bool)isUserAuthenticated;
- (void)applyPendingTransactions:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (_Bool)isPendingTransactions;
- (void)makePayment:(id)arg1 categoryID:(long long)arg2 showOnly:(_Bool)arg3 failure:(CDUnknownBlockType)arg4;
- (void)makePayment:(id)arg1 failure:(CDUnknownBlockType)arg2;
- (void)internalGameCentreLoginExists:(CDUnknownBlockType)arg1;
- (void)gameCentreLoginExists:(id)arg1 response:(CDUnknownBlockType)arg2;
- (void)internalLoginWithGameCentre:(CDUnknownBlockType)arg1;
- (void)loginWithGameCentre:(id)arg1 response:(CDUnknownBlockType)arg2;
- (void)ssoTokenRequest:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)getSSOToken:(_Bool)arg1 callback:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getSSOToken:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithConfiguration:(id)arg1;

@end

