//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface MobileAuthConfiguration : NSObject
{
    NSString *_issuer;
    NSString *_clientID;
    NSString *_clientSecret;
    NSString *_redirectURI;
    NSString *_paymentURI;
    NSString *_shopID;
    NSArray *_scopes;
}

@property(readonly, nonatomic) NSArray *scopes; // @synthesize scopes=_scopes;
@property(readonly, nonatomic) NSString *shopID; // @synthesize shopID=_shopID;
@property(readonly, nonatomic) NSString *paymentURI; // @synthesize paymentURI=_paymentURI;
@property(readonly, nonatomic) NSString *redirectURI; // @synthesize redirectURI=_redirectURI;
@property(readonly, nonatomic) NSString *clientSecret; // @synthesize clientSecret=_clientSecret;
@property(readonly, nonatomic) NSString *clientID; // @synthesize clientID=_clientID;
@property(readonly, nonatomic) NSString *issuer; // @synthesize issuer=_issuer;
- (void).cxx_destruct;
- (_Bool)validateURL:(id)arg1;
- (id)verifyUrl:(id)arg1;
- (void)verifyConfig;
- (id)getLookupURL;
- (id)getCompletionURL;
- (id)getShopURL;
- (id)initMobileAuthConfig:(id)arg1 clientID:(id)arg2 clientSecret:(id)arg3 redirectURI:(id)arg4 paymentURI:(id)arg5 shopID:(id)arg6 scopes:(id)arg7;

@end

