//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, OIDAuthState;

@protocol OIDAuthStateErrorDelegate <NSObject>
- (void)authState:(OIDAuthState *)arg1 didEncounterAuthorizationError:(NSError *)arg2;

@optional
- (void)authState:(OIDAuthState *)arg1 didEncounterTransientError:(NSError *)arg2;
@end

