//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OIDAuthorizationFlowSession-Protocol.h"
#import "OIDExternalUserAgentSession-Protocol.h"

@class NSString, OIDAuthorizationRequest;
@protocol OIDExternalUserAgent;

@interface OIDAuthorizationFlowSessionImplementation : NSObject <OIDExternalUserAgentSession, OIDAuthorizationFlowSession>
{
    OIDAuthorizationRequest *_request;
    id <OIDExternalUserAgent> _externalUserAgent;
    CDUnknownBlockType _pendingauthorizationFlowCallback;
}

- (void).cxx_destruct;
- (_Bool)resumeAuthorizationFlowWithURL:(id)arg1;
- (void)failAuthorizationFlowWithError:(id)arg1;
- (void)didFinishWithResponse:(id)arg1 error:(id)arg2;
- (void)failExternalUserAgentFlowWithError:(id)arg1;
- (_Bool)resumeExternalUserAgentFlowWithURL:(id)arg1;
- (_Bool)shouldHandleURL:(id)arg1;
- (void)cancel;
- (void)presentAuthorizationWithExternalUserAgent:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (id)initWithRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

