//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CADisplayLink, CAEAGLLayer;

@interface OpenGLViewBacking : UIView
{
    CAEAGLLayer *_eaglLayer;
    struct OpenGLView *m_JagOpenGLView;
    CADisplayLink *m_DisplayLink;
}

+ (Class)layerClass;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (struct CGPoint)getTouchInBackingCoords:(struct CGPoint)arg1;
- (void)render:(id)arg1;
- (void)setupLayer;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 withOpenGLView:(struct OpenGLView *)arg2;
- (void)stopUpdating;
- (void)startUpdating;
- (void)setupDisplayLink;

@end

