//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, SKPaymentTransaction;

@protocol PackageScrollViewDelagate
- (void)adjustCollapsedMargin:(unsigned char)arg1 itemsCount:(long long)arg2;
- (void)onItemPurchased:(SKPaymentTransaction *)arg1;
- (void)onPackageExpandCollapse:(_Bool)arg1;
- (void)onDisplayMessage:(NSString *)arg1 message:(NSString *)arg2;
@end

