//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface PackageItemsPresenter : NSObject
{
    id delegate;
    NSMutableArray *products;
}

- (void).cxx_destruct;
- (void)purchaseProduct:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

