//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

#import "ItemPresenter-Protocol.h"
#import "ToggleProgressViewDelegate-Protocol.h"

@class JagexCategory, NSMutableArray, PackageItemsPresenter, UICollectionView;

@interface PackageItemsViewController : UICollectionViewController <ItemPresenter, ToggleProgressViewDelegate>
{
    id delegate;
    NSMutableArray *products;
    PackageItemsPresenter *presenter;
    _Bool showMoreProducts;
    JagexCategory *jagexPackage;
    UICollectionView *collectionView;
}

@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView;
@property(retain, nonatomic) JagexCategory *jagexPackage; // @synthesize jagexPackage;
- (void).cxx_destruct;
- (double)findFontSizeforLabel:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)toggleProgressView:(_Bool)arg1 blockUserInteraction:(_Bool)arg2;
- (void)toggleProgressView:(_Bool)arg1;
- (void)onItemPurchased:(id)arg1;
- (void)onDisplayMessage:(id)arg1 message:(id)arg2;
- (void)dismissView;
- (void)didReceiveMemoryWarning;
- (void)hideRevealMoreProducts:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithDelegate:(id)arg1;

@end

