//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "PackageItemsViewDelagate-Protocol.h"
#import "ToggleProgressViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UIScrollView;

@interface PackageScrollView : UIView <PackageItemsViewDelagate, ToggleProgressViewDelegate, UIScrollViewDelegate>
{
    id delegate;
    UIScrollView *packageScrollView;
    NSMutableArray *jagexPackages;
    unsigned char isExpandedMode;
    long long selectedViewId;
    long long m_categoryID;
    _Bool m_showOnly;
}

- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (struct CGSize)scrollViewIntermediateContentSize;
- (struct CGSize)scrollViewContentSize:(float)arg1;
- (void)loadData:(id)arg1 forExpandedView:(id)arg2;
- (void)expandRemainingViews:(id)arg1;
- (void)expandSelectedViewAndAlign:(id)arg1;
- (void)onViewClicked:(id)arg1;
- (void)removeCollapsedPackageViews;
- (void)addCollapsedPackageViews;
- (void)toggleProgressView:(_Bool)arg1 blockUserInteraction:(_Bool)arg2;
- (void)toggleProgressView:(_Bool)arg1;
- (void)onDisplayMessage:(id)arg1 message:(id)arg2;
- (void)onItemPurchased:(id)arg1;
- (void)displayPackages;
- (long long)getPositionForCategoryID:(id)arg1 categoryID:(long long)arg2;
- (id)filterPackages:(id)arg1 categoryID:(long long)arg2;
- (void)onPackagesLoaded:(id)arg1;
- (void)collapseCell:(id)arg1 atPosition:(long long)arg2 withPackage:(id)arg3;
- (void)collapsePackageViews;
- (void)collapsePackages;
- (id)initWithScrollViewAndCategoryIDAndShowOnly:(id)arg1 delegate:(id)arg2 categoryID:(long long)arg3 showOnly:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

