//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel, UIView;

@interface ProductCollectionViewCell : UICollectionViewCell
{
    UILabel *_productTitle;
    UILabel *_productSubTitle;
    UILabel *_trialPeroidLabel;
    UILabel *_productPrice;
    UIImageView *_recommendedIcon;
    UILabel *_orginalProductPrice;
    UILabel *_purchaseButtonLabel;
    UIView *_purchaseButtonBackground;
}

@property(nonatomic) __weak UIView *purchaseButtonBackground; // @synthesize purchaseButtonBackground=_purchaseButtonBackground;
@property(nonatomic) __weak UILabel *purchaseButtonLabel; // @synthesize purchaseButtonLabel=_purchaseButtonLabel;
@property(nonatomic) __weak UILabel *orginalProductPrice; // @synthesize orginalProductPrice=_orginalProductPrice;
@property(nonatomic) __weak UIImageView *recommendedIcon; // @synthesize recommendedIcon=_recommendedIcon;
@property(nonatomic) __weak UILabel *productPrice; // @synthesize productPrice=_productPrice;
@property(nonatomic) __weak UILabel *trialPeroidLabel; // @synthesize trialPeroidLabel=_trialPeroidLabel;
@property(nonatomic) __weak UILabel *productSubTitle; // @synthesize productSubTitle=_productSubTitle;
@property(nonatomic) __weak UILabel *productTitle; // @synthesize productTitle=_productTitle;
- (void).cxx_destruct;

@end

