//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface PurchaseHistory : NSObject
{
    NSMutableArray *purchaseHistory;
}

@property(retain) NSMutableArray *purchaseHistory; // @synthesize purchaseHistory;
- (void).cxx_destruct;
- (_Bool)isSubForCurrentUser:(id)arg1;
- (_Bool)isUserElegibleForOffer;
- (id)initWithDictionary:(id)arg1;
- (id)initWithPurchaseHistory:(id)arg1;

@end

