//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PurchaseLookup : NSObject
{
    _Bool trialPeriod;
    _Bool introPricePeriod;
    _Bool authUser;
    NSString *originalTransactionId;
    NSString *productId;
}

@property(nonatomic) _Bool authUser; // @synthesize authUser;
@property(nonatomic) _Bool introPricePeriod; // @synthesize introPricePeriod;
@property(nonatomic) _Bool trialPeriod; // @synthesize trialPeriod;
@property(retain, nonatomic) NSString *productId; // @synthesize productId;
@property(retain, nonatomic) NSString *originalTransactionId; // @synthesize originalTransactionId;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)initPurchaseLookupFromDictionary:(id)arg1;
- (id)initWithOrginalTransactionId:(id)arg1 productId:(id)arg2 trialPeroid:(_Bool)arg3 introPricePeroid:(_Bool)arg4 authUser:(_Bool)arg5;

@end

