//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Reachability;

@interface ReachabilityWrapper : NSObject
{
    Reachability *reachability;
    CDUnknownBlockType reachabilityChanged;
}

- (void).cxx_destruct;
- (void)isConnectionAvailable:(CDUnknownBlockType)arg1;
- (void)updateInterfaceWithReachability:(id)arg1;
- (void)reachabilityChanged:(id)arg1;
- (id)init;

@end

