//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface Shop : NSObject
{
    NSString *_imageLogo;
    NSString *_imageBackground;
    NSMutableArray *_jagexPackages;
}

@property(readonly, nonatomic) NSMutableArray *jagexPackages; // @synthesize jagexPackages=_jagexPackages;
@property(readonly, nonatomic) NSString *imageBackground; // @synthesize imageBackground=_imageBackground;
@property(readonly, nonatomic) NSString *imageLogo; // @synthesize imageLogo=_imageLogo;
- (void).cxx_destruct;
- (id)initShopWithDictionary:(id)arg1;

@end

