//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSError, NSString;

@protocol StorePresenterDelegate
- (void)closeShopWithMessage:(NSString *)arg1 andTitle:(NSString *)arg2;
- (void)onReportError:(NSError *)arg1;
- (void)onShopLoadedWithBackground:(NSString *)arg1 logo:(NSString *)arg2;
- (void)onPackagesLoaded:(NSArray *)arg1;
- (void)onDisplayMessage:(NSString *)arg1 message:(NSString *)arg2;
- (void)onIncompleteTransactionsAvailable;
@end

