//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (Jagex)
- (id)formatPrice:(id)arg1 locale:(id)arg2;
- (void)setPriceAppended:(id)arg1 price:(id)arg2 locale:(id)arg3;
- (void)setPrice:(id)arg1 locale:(id)arg2;
- (void)adjustFontSizeToFillItsContents;
@end

